version: '3.9'
services:
  nextjs:
    image: node:18-alpine
    container_name: mealspots-web
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env.local
